/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'revenue' : bigint,
  'totalPrints' : bigint,
  'offlineDevices' : bigint,
  'onlineDevices' : bigint,
}
export type AllowedExtension = { 'doc' : null } |
  { 'jpg' : null } |
  { 'pdf' : null } |
  { 'png' : null } |
  { 'docx' : null } |
  { 'jpeg' : null };
export interface AnalysisResultView {
  'nearlyBlankPages' : Array<bigint>,
  'lowContentPages' : Array<bigint>,
  'blankPages' : Array<bigint>,
  'fileId' : FileId,
  'analyzedAt' : Timestamp,
  'totalPages' : bigint,
  'colorPages' : Array<bigint>,
  'contentPageCount' : bigint,
  'issueNotes' : Array<string>,
}
export interface Cell { 'value' : Value, 'name' : string }
export type ColorMode = { 'BlackAndWhite' : null } |
  { 'Color' : null };
export interface ConnectResult {
  'state' : string,
  'connected' : boolean,
  'printerId' : PrinterId,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FileId = bigint;
export type JobId = bigint;
export type JobRef = string;
export type JobStatus = { 'Printing' : null } |
  { 'Failed' : null } |
  { 'Uploaded' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export interface PageAnalysisInput {
  'nearlyBlankPages' : Array<bigint>,
  'lowContentPages' : Array<bigint>,
  'blankPages' : Array<bigint>,
  'totalPages' : bigint,
  'colorPages' : Array<bigint>,
}
export type PageSelection = { 'All' : null } |
  { 'Custom' : null };
export type PaperSize = { 'A3' : null } |
  { 'A4' : null };
export interface PrintJobView {
  'id' : JobId,
  'status' : JobStatus,
  'estimatedPrice' : bigint,
  'printedPages' : bigint,
  'createdAt' : Timestamp,
  'fileName' : string,
  'updatedAt' : Timestamp,
  'fileId' : FileId,
  'jobRef' : JobRef,
  'sizeBytes' : bigint,
  'printerId' : PrinterId,
  'options' : PrintOptions,
  'pageCount' : bigint,
}
export interface PrintOptions {
  'colorMode' : ColorMode,
  'excludedBlankPages' : Array<bigint>,
  'pageSelection' : PageSelection,
  'paperSize' : PaperSize,
  'customRange' : [] | [string],
  'copies' : bigint,
}
export interface PrintProgress {
  'status' : JobStatus,
  'printedPages' : bigint,
  'jobId' : JobId,
  'updatedAt' : Timestamp,
  'totalPages' : bigint,
}
export type PrinterId = string;
export interface PrinterStatus {
  'isOnline' : boolean,
  'updatedAt' : Timestamp,
  'state' : string,
  'activeJobId' : [] | [JobId],
  'printerId' : PrinterId,
}
export interface PrinterView {
  'id' : PrinterId,
  'paperSizes' : Array<PaperSize>,
  'colorModes' : Array<ColorMode>,
  'speedPagesPerMinute' : bigint,
  'name' : string,
  'isOnline' : boolean,
  'description' : string,
  'openingHours' : string,
  'rating' : bigint,
  'location' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UploadValidation = { 'ok' : AllowedExtension } |
  { 'unsupportedExtension' : string } |
  { 'tooLarge' : { 'actualBytes' : bigint, 'limitBytes' : bigint } } |
  { 'empty' : null };
export interface UploadedFileView {
  'id' : FileId,
  'contentType' : string,
  'fileName' : string,
  'sizeBytes' : bigint,
  'pageCount' : bigint,
  'uploadedAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalPrints' : bigint,
  'totalSpent' : bigint,
  'savedFiles' : bigint,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Persist the real per-page analysis for an uploaded file.
   * /
   * / The page arrays are computed from the actual PDF content by the client
   * / (pdf.js) and submitted here; the backend validates them against the
   * / document's real page count and stores the result.
   */
  'analyzeFile' : ActorMethod<[bigint, PageAnalysisInput], AnalysisResultView>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Cancel a job that has not completed.
   */
  'cancelJob' : ActorMethod<[JobId], PrintJobView>,
  /**
   * / Simulated connect to a printer device.
   */
  'connectPrinter' : ActorMethod<[string], ConnectResult>,
  /**
   * / Create a print job and start printing immediately.
   * /
   * / There is no payment step and no printer selection: the job is routed
   * / through the PrintHub portable device automatically.
   */
  'createJob' : ActorMethod<[bigint, PrintOptions], PrintJobView>,
  /**
   * / Compute the estimated price for a job from its options.
   */
  'estimatePrice' : ActorMethod<[bigint, PrintOptions], bigint>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Aggregate statistics for the admin dashboard. Admin-only.
   */
  'getAdminStats' : ActorMethod<[], AdminStats>,
  /**
   * / Fetch a stored analysis result for a file.
   */
  'getAnalysis' : ActorMethod<[bigint], [] | [AnalysisResultView]>,
  /**
   * / Return the PrintHub backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch an uploaded file's metadata by id.
   */
  'getFile' : ActorMethod<[bigint], [] | [UploadedFileView]>,
  /**
   * / Fetch a print job by id.
   */
  'getJob' : ActorMethod<[JobId], [] | [PrintJobView]>,
  /**
   * / Read the simulated progress of a job.
   */
  'getPrintProgress' : ActorMethod<[JobId], [] | [PrintProgress]>,
  /**
   * / Fetch a single printer by id.
   */
  'getPrinter' : ActorMethod<[string], [] | [PrinterView]>,
  /**
   * / Simulated live status of a printer device.
   */
  'getPrinterStatus' : ActorMethod<[string], [] | [PrinterStatus]>,
  /**
   * / Aggregate statistics for the caller's dashboard.
   */
  'getUserStats' : ActorMethod<[], UserStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's uploaded files.
   */
  'listFiles' : ActorMethod<[], Array<UploadedFileView>>,
  /**
   * / List the caller's print jobs, newest first.
   */
  'listJobs' : ActorMethod<[], Array<PrintJobView>>,
  /**
   * / List every printer in the network.
   */
  'listPrinters' : ActorMethod<[], Array<PrinterView>>,
  /**
   * / Register an uploaded file's metadata after its bytes are stored.
   */
  'registerFile' : ActorMethod<
    [string, string, bigint, bigint],
    UploadedFileView
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search printers by name or location.
   */
  'searchPrinters' : ActorMethod<[string], Array<PrinterView>>,
  /**
   * / Advance simulated printing for all in-flight jobs.
   */
  'tickPrinting' : ActorMethod<[], undefined>,
  /**
   * / Validate an upload's file name and size before its bytes are stored.
   */
  'validateUpload' : ActorMethod<[string, bigint], UploadValidation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];