/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const PageAnalysisInput = IDL.Record({
  'nearlyBlankPages' : IDL.Vec(IDL.Nat),
  'lowContentPages' : IDL.Vec(IDL.Nat),
  'blankPages' : IDL.Vec(IDL.Nat),
  'totalPages' : IDL.Nat,
  'colorPages' : IDL.Vec(IDL.Nat),
});
export const FileId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AnalysisResultView = IDL.Record({
  'nearlyBlankPages' : IDL.Vec(IDL.Nat),
  'lowContentPages' : IDL.Vec(IDL.Nat),
  'blankPages' : IDL.Vec(IDL.Nat),
  'fileId' : FileId,
  'analyzedAt' : Timestamp,
  'totalPages' : IDL.Nat,
  'colorPages' : IDL.Vec(IDL.Nat),
  'contentPageCount' : IDL.Nat,
  'issueNotes' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'Printing' : IDL.Null,
  'Failed' : IDL.Null,
  'Uploaded' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const JobRef = IDL.Text;
export const PrinterId = IDL.Text;
export const ColorMode = IDL.Variant({
  'BlackAndWhite' : IDL.Null,
  'Color' : IDL.Null,
});
export const PageSelection = IDL.Variant({
  'All' : IDL.Null,
  'Custom' : IDL.Null,
});
export const PaperSize = IDL.Variant({ 'A3' : IDL.Null, 'A4' : IDL.Null });
export const PrintOptions = IDL.Record({
  'colorMode' : ColorMode,
  'excludedBlankPages' : IDL.Vec(IDL.Nat),
  'pageSelection' : PageSelection,
  'paperSize' : PaperSize,
  'customRange' : IDL.Opt(IDL.Text),
  'copies' : IDL.Nat,
});
export const PrintJobView = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'estimatedPrice' : IDL.Nat,
  'printedPages' : IDL.Nat,
  'createdAt' : Timestamp,
  'fileName' : IDL.Text,
  'updatedAt' : Timestamp,
  'fileId' : FileId,
  'jobRef' : JobRef,
  'sizeBytes' : IDL.Nat,
  'printerId' : PrinterId,
  'options' : PrintOptions,
  'pageCount' : IDL.Nat,
});
export const ConnectResult = IDL.Record({
  'state' : IDL.Text,
  'connected' : IDL.Bool,
  'printerId' : PrinterId,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AdminStats = IDL.Record({
  'revenue' : IDL.Nat,
  'totalPrints' : IDL.Nat,
  'offlineDevices' : IDL.Nat,
  'onlineDevices' : IDL.Nat,
});
export const UploadedFileView = IDL.Record({
  'id' : FileId,
  'contentType' : IDL.Text,
  'fileName' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'pageCount' : IDL.Nat,
  'uploadedAt' : Timestamp,
});
export const PrintProgress = IDL.Record({
  'status' : JobStatus,
  'printedPages' : IDL.Nat,
  'jobId' : JobId,
  'updatedAt' : Timestamp,
  'totalPages' : IDL.Nat,
});
export const PrinterView = IDL.Record({
  'id' : PrinterId,
  'paperSizes' : IDL.Vec(PaperSize),
  'colorModes' : IDL.Vec(ColorMode),
  'speedPagesPerMinute' : IDL.Nat,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'description' : IDL.Text,
  'openingHours' : IDL.Text,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
});
export const PrinterStatus = IDL.Record({
  'isOnline' : IDL.Bool,
  'updatedAt' : Timestamp,
  'state' : IDL.Text,
  'activeJobId' : IDL.Opt(JobId),
  'printerId' : PrinterId,
});
export const UserStats = IDL.Record({
  'totalPrints' : IDL.Nat,
  'totalSpent' : IDL.Nat,
  'savedFiles' : IDL.Nat,
});
export const AllowedExtension = IDL.Variant({
  'doc' : IDL.Null,
  'jpg' : IDL.Null,
  'pdf' : IDL.Null,
  'png' : IDL.Null,
  'docx' : IDL.Null,
  'jpeg' : IDL.Null,
});
export const UploadValidation = IDL.Variant({
  'ok' : AllowedExtension,
  'unsupportedExtension' : IDL.Text,
  'tooLarge' : IDL.Record({ 'actualBytes' : IDL.Nat, 'limitBytes' : IDL.Nat }),
  'empty' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'analyzeFile' : IDL.Func(
      [IDL.Nat, PageAnalysisInput],
      [AnalysisResultView],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelJob' : IDL.Func([JobId], [PrintJobView], []),
  'connectPrinter' : IDL.Func([IDL.Text], [ConnectResult], []),
  'createJob' : IDL.Func([IDL.Nat, PrintOptions], [PrintJobView], []),
  'estimatePrice' : IDL.Func([IDL.Nat, PrintOptions], [IDL.Nat], ['query']),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAnalysis' : IDL.Func([IDL.Nat], [IDL.Opt(AnalysisResultView)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Nat], [IDL.Opt(UploadedFileView)], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(PrintJobView)], ['query']),
  'getPrintProgress' : IDL.Func([JobId], [IDL.Opt(PrintProgress)], ['query']),
  'getPrinter' : IDL.Func([IDL.Text], [IDL.Opt(PrinterView)], ['query']),
  'getPrinterStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PrinterStatus)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFiles' : IDL.Func([], [IDL.Vec(UploadedFileView)], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(PrintJobView)], ['query']),
  'listPrinters' : IDL.Func([], [IDL.Vec(PrinterView)], ['query']),
  'registerFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [UploadedFileView],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchPrinters' : IDL.Func([IDL.Text], [IDL.Vec(PrinterView)], ['query']),
  'tickPrinting' : IDL.Func([], [], []),
  'validateUpload' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [UploadValidation],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const PageAnalysisInput = IDL.Record({
    'nearlyBlankPages' : IDL.Vec(IDL.Nat),
    'lowContentPages' : IDL.Vec(IDL.Nat),
    'blankPages' : IDL.Vec(IDL.Nat),
    'totalPages' : IDL.Nat,
    'colorPages' : IDL.Vec(IDL.Nat),
  });
  const FileId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AnalysisResultView = IDL.Record({
    'nearlyBlankPages' : IDL.Vec(IDL.Nat),
    'lowContentPages' : IDL.Vec(IDL.Nat),
    'blankPages' : IDL.Vec(IDL.Nat),
    'fileId' : FileId,
    'analyzedAt' : Timestamp,
    'totalPages' : IDL.Nat,
    'colorPages' : IDL.Vec(IDL.Nat),
    'contentPageCount' : IDL.Nat,
    'issueNotes' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobId = IDL.Nat;
  const JobStatus = IDL.Variant({
    'Printing' : IDL.Null,
    'Failed' : IDL.Null,
    'Uploaded' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const JobRef = IDL.Text;
  const PrinterId = IDL.Text;
  const ColorMode = IDL.Variant({
    'BlackAndWhite' : IDL.Null,
    'Color' : IDL.Null,
  });
  const PageSelection = IDL.Variant({ 'All' : IDL.Null, 'Custom' : IDL.Null });
  const PaperSize = IDL.Variant({ 'A3' : IDL.Null, 'A4' : IDL.Null });
  const PrintOptions = IDL.Record({
    'colorMode' : ColorMode,
    'excludedBlankPages' : IDL.Vec(IDL.Nat),
    'pageSelection' : PageSelection,
    'paperSize' : PaperSize,
    'customRange' : IDL.Opt(IDL.Text),
    'copies' : IDL.Nat,
  });
  const PrintJobView = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'estimatedPrice' : IDL.Nat,
    'printedPages' : IDL.Nat,
    'createdAt' : Timestamp,
    'fileName' : IDL.Text,
    'updatedAt' : Timestamp,
    'fileId' : FileId,
    'jobRef' : JobRef,
    'sizeBytes' : IDL.Nat,
    'printerId' : PrinterId,
    'options' : PrintOptions,
    'pageCount' : IDL.Nat,
  });
  const ConnectResult = IDL.Record({
    'state' : IDL.Text,
    'connected' : IDL.Bool,
    'printerId' : PrinterId,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AdminStats = IDL.Record({
    'revenue' : IDL.Nat,
    'totalPrints' : IDL.Nat,
    'offlineDevices' : IDL.Nat,
    'onlineDevices' : IDL.Nat,
  });
  const UploadedFileView = IDL.Record({
    'id' : FileId,
    'contentType' : IDL.Text,
    'fileName' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'pageCount' : IDL.Nat,
    'uploadedAt' : Timestamp,
  });
  const PrintProgress = IDL.Record({
    'status' : JobStatus,
    'printedPages' : IDL.Nat,
    'jobId' : JobId,
    'updatedAt' : Timestamp,
    'totalPages' : IDL.Nat,
  });
  const PrinterView = IDL.Record({
    'id' : PrinterId,
    'paperSizes' : IDL.Vec(PaperSize),
    'colorModes' : IDL.Vec(ColorMode),
    'speedPagesPerMinute' : IDL.Nat,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'description' : IDL.Text,
    'openingHours' : IDL.Text,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
  });
  const PrinterStatus = IDL.Record({
    'isOnline' : IDL.Bool,
    'updatedAt' : Timestamp,
    'state' : IDL.Text,
    'activeJobId' : IDL.Opt(JobId),
    'printerId' : PrinterId,
  });
  const UserStats = IDL.Record({
    'totalPrints' : IDL.Nat,
    'totalSpent' : IDL.Nat,
    'savedFiles' : IDL.Nat,
  });
  const AllowedExtension = IDL.Variant({
    'doc' : IDL.Null,
    'jpg' : IDL.Null,
    'pdf' : IDL.Null,
    'png' : IDL.Null,
    'docx' : IDL.Null,
    'jpeg' : IDL.Null,
  });
  const UploadValidation = IDL.Variant({
    'ok' : AllowedExtension,
    'unsupportedExtension' : IDL.Text,
    'tooLarge' : IDL.Record({
      'actualBytes' : IDL.Nat,
      'limitBytes' : IDL.Nat,
    }),
    'empty' : IDL.Null,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'analyzeFile' : IDL.Func(
        [IDL.Nat, PageAnalysisInput],
        [AnalysisResultView],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelJob' : IDL.Func([JobId], [PrintJobView], []),
    'connectPrinter' : IDL.Func([IDL.Text], [ConnectResult], []),
    'createJob' : IDL.Func([IDL.Nat, PrintOptions], [PrintJobView], []),
    'estimatePrice' : IDL.Func([IDL.Nat, PrintOptions], [IDL.Nat], ['query']),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAnalysis' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(AnalysisResultView)],
        ['query'],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Nat], [IDL.Opt(UploadedFileView)], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(PrintJobView)], ['query']),
    'getPrintProgress' : IDL.Func([JobId], [IDL.Opt(PrintProgress)], ['query']),
    'getPrinter' : IDL.Func([IDL.Text], [IDL.Opt(PrinterView)], ['query']),
    'getPrinterStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PrinterStatus)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFiles' : IDL.Func([], [IDL.Vec(UploadedFileView)], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(PrintJobView)], ['query']),
    'listPrinters' : IDL.Func([], [IDL.Vec(PrinterView)], ['query']),
    'registerFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [UploadedFileView],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchPrinters' : IDL.Func([IDL.Text], [IDL.Vec(PrinterView)], ['query']),
    'tickPrinting' : IDL.Func([], [], []),
    'validateUpload' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [UploadValidation],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };