/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AdminStats {
    revenue: bigint;
    totalPrints: bigint;
    offlineDevices: bigint;
    onlineDevices: bigint;
}
export interface AnalysisResultView {
    nearlyBlankPages: Array<bigint>;
    lowContentPages: Array<bigint>;
    blankPages: Array<bigint>;
    fileId: FileId;
    analyzedAt: Timestamp;
    totalPages: bigint;
    colorPages: Array<bigint>;
    contentPageCount: bigint;
    issueNotes: Array<string>;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ConnectResult {
    state: string;
    connected: boolean;
    printerId: PrinterId;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type FileId = bigint;
export type JobId = bigint;
export type JobRef = string;
export interface PageAnalysisInput {
    nearlyBlankPages: Array<bigint>;
    lowContentPages: Array<bigint>;
    blankPages: Array<bigint>;
    totalPages: bigint;
    colorPages: Array<bigint>;
}
export interface PrintJobView {
    id: JobId;
    status: JobStatus;
    estimatedPrice: bigint;
    printedPages: bigint;
    createdAt: Timestamp;
    fileName: string;
    updatedAt: Timestamp;
    fileId: FileId;
    jobRef: JobRef;
    sizeBytes: bigint;
    printerId: PrinterId;
    options: PrintOptions;
    pageCount: bigint;
}
export interface PrintOptions {
    colorMode: ColorMode;
    excludedBlankPages: Array<bigint>;
    pageSelection: PageSelection;
    paperSize: PaperSize;
    customRange?: string;
    copies: bigint;
}
export interface PrintProgress {
    status: JobStatus;
    printedPages: bigint;
    jobId: JobId;
    updatedAt: Timestamp;
    totalPages: bigint;
}
export type PrinterId = string;
export interface PrinterStatus {
    isOnline: boolean;
    updatedAt: Timestamp;
    state: string;
    activeJobId?: JobId;
    printerId: PrinterId;
}
export interface PrinterView {
    id: PrinterId;
    paperSizes: Array<PaperSize>;
    colorModes: Array<ColorMode>;
    speedPagesPerMinute: bigint;
    name: string;
    isOnline: boolean;
    description: string;
    openingHours: string;
    rating: bigint;
    location: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Timestamp = bigint;
export type UploadValidation = {
    __kind__: "ok";
    ok: AllowedExtension;
} | {
    __kind__: "unsupportedExtension";
    unsupportedExtension: string;
} | {
    __kind__: "tooLarge";
    tooLarge: {
        actualBytes: bigint;
        limitBytes: bigint;
    };
} | {
    __kind__: "empty";
    empty: null;
};
export interface UploadedFileView {
    id: FileId;
    contentType: string;
    fileName: string;
    sizeBytes: bigint;
    pageCount: bigint;
    uploadedAt: Timestamp;
}
export interface UserStats {
    totalPrints: bigint;
    totalSpent: bigint;
    savedFiles: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AllowedExtension {
    doc = "doc",
    jpg = "jpg",
    pdf = "pdf",
    png = "png",
    docx = "docx",
    jpeg = "jpeg"
}
export enum ColorMode {
    BlackAndWhite = "BlackAndWhite",
    Color = "Color"
}
export enum JobStatus {
    Printing = "Printing",
    Failed = "Failed",
    Uploaded = "Uploaded",
    Cancelled = "Cancelled",
    Completed = "Completed"
}
export enum PageSelection {
    All = "All",
    Custom = "Custom"
}
export enum PaperSize {
    A3 = "A3",
    A4 = "A4"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Persist the real per-page analysis for an uploaded file.
     * /
     * / The page arrays are computed from the actual PDF content by the client
     * / (pdf.js) and submitted here; the backend validates them against the
     * / document's real page count and stores the result.
     */
    analyzeFile(fileId: bigint, input: PageAnalysisInput): Promise<AnalysisResultView>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Cancel a job that has not completed.
     */
    cancelJob(jobId: JobId): Promise<PrintJobView>;
    /**
     * / Simulated connect to a printer device.
     */
    connectPrinter(printerId: string): Promise<ConnectResult>;
    /**
     * / Create a print job and start printing immediately.
     * /
     * / There is no payment step and no printer selection: the job is routed
     * / through the PrintHub portable device automatically.
     */
    createJob(fileId: bigint, options: PrintOptions): Promise<PrintJobView>;
    /**
     * / Compute the estimated price for a job from its options.
     */
    estimatePrice(pageCount: bigint, options: PrintOptions): Promise<bigint>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Aggregate statistics for the admin dashboard. Admin-only.
     */
    getAdminStats(): Promise<AdminStats>;
    /**
     * / Fetch a stored analysis result for a file.
     */
    getAnalysis(fileId: bigint): Promise<AnalysisResultView | null>;
    /**
     * / Return the PrintHub backend API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch an uploaded file's metadata by id.
     */
    getFile(fileId: bigint): Promise<UploadedFileView | null>;
    /**
     * / Fetch a print job by id.
     */
    getJob(jobId: JobId): Promise<PrintJobView | null>;
    /**
     * / Read the simulated progress of a job.
     */
    getPrintProgress(jobId: JobId): Promise<PrintProgress | null>;
    /**
     * / Fetch a single printer by id.
     */
    getPrinter(printerId: string): Promise<PrinterView | null>;
    /**
     * / Simulated live status of a printer device.
     */
    getPrinterStatus(printerId: string): Promise<PrinterStatus | null>;
    /**
     * / Aggregate statistics for the caller's dashboard.
     */
    getUserStats(): Promise<UserStats>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's uploaded files.
     */
    listFiles(): Promise<Array<UploadedFileView>>;
    /**
     * / List the caller's print jobs, newest first.
     */
    listJobs(): Promise<Array<PrintJobView>>;
    /**
     * / List every printer in the network.
     */
    listPrinters(): Promise<Array<PrinterView>>;
    /**
     * / Register an uploaded file's metadata after its bytes are stored.
     */
    registerFile(fileName: string, contentType: string, sizeBytes: bigint, pageCount: bigint): Promise<UploadedFileView>;
    schema(): Promise<string>;
    /**
     * / Search printers by name or location.
     */
    searchPrinters(searchTerm: string): Promise<Array<PrinterView>>;
    /**
     * / Advance simulated printing for all in-flight jobs.
     */
    tickPrinting(): Promise<void>;
    /**
     * / Validate an upload's file name and size before its bytes are stored.
     */
    validateUpload(fileName: string, sizeBytes: bigint): Promise<UploadValidation>;
}
import type { AllowedExtension as _AllowedExtension, AnalysisResultView as _AnalysisResultView, Cell as _Cell, ColorMode as _ColorMode, Error as _Error, FileId as _FileId, JobId as _JobId, JobRef as _JobRef, JobStatus as _JobStatus, PageSelection as _PageSelection, PaperSize as _PaperSize, PrintJobView as _PrintJobView, PrintOptions as _PrintOptions, PrintProgress as _PrintProgress, PrinterId as _PrinterId, PrinterStatus as _PrinterStatus, PrinterView as _PrinterView, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UploadValidation as _UploadValidation, UploadedFileView as _UploadedFileView, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async analyzeFile(arg0: bigint, arg1: PageAnalysisInput): Promise<AnalysisResultView> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeFile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeFile(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelJob(arg0: JobId): Promise<PrintJobView> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelJob(arg0);
                return from_candid_PrintJobView_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelJob(arg0);
            return from_candid_PrintJobView_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async connectPrinter(arg0: string): Promise<ConnectResult> {
        if (this.processError) {
            try {
                const result = await this.actor.connectPrinter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectPrinter(arg0);
            return result;
        }
    }
    async createJob(arg0: bigint, arg1: PrintOptions): Promise<PrintJobView> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0, to_candid_PrintOptions_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PrintJobView_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0, to_candid_PrintOptions_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PrintJobView_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async estimatePrice(arg0: bigint, arg1: PrintOptions): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.estimatePrice(arg0, to_candid_PrintOptions_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimatePrice(arg0, to_candid_PrintOptions_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAnalysis(arg0: bigint): Promise<AnalysisResultView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFile(arg0: bigint): Promise<UploadedFileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: JobId): Promise<PrintJobView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrintProgress(arg0: JobId): Promise<PrintProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrintProgress(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrintProgress(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrinter(arg0: string): Promise<PrinterView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrinter(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrinter(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrinterStatus(arg0: string): Promise<PrinterStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrinterStatus(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrinterStatus(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFiles(): Promise<Array<UploadedFileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFiles();
            return result;
        }
    }
    async listJobs(): Promise<Array<PrintJobView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPrinters(): Promise<Array<PrinterView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPrinters();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPrinters();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerFile(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<UploadedFileView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchPrinters(arg0: string): Promise<Array<PrinterView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPrinters(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPrinters(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async tickPrinting(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.tickPrinting();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tickPrinting();
            return result;
        }
    }
    async validateUpload(arg0: string, arg1: bigint): Promise<UploadValidation> {
        if (this.processError) {
            try {
                const result = await this.actor.validateUpload(arg0, arg1);
                return from_candid_UploadValidation_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateUpload(arg0, arg1);
            return from_candid_UploadValidation_n46(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AllowedExtension_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AllowedExtension): AllowedExtension {
    return "doc" in value ? AllowedExtension.doc : "jpg" in value ? AllowedExtension.jpg : "pdf" in value ? AllowedExtension.pdf : "png" in value ? AllowedExtension.png : "docx" in value ? AllowedExtension.docx : "jpeg" in value ? AllowedExtension.jpeg : value;
}
function from_candid_Cell_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ColorMode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorMode): ColorMode {
    return "BlackAndWhite" in value ? ColorMode.BlackAndWhite : "Color" in value ? ColorMode.Color : value;
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return "Printing" in value ? JobStatus.Printing : "Failed" in value ? JobStatus.Failed : "Uploaded" in value ? JobStatus.Uploaded : "Cancelled" in value ? JobStatus.Cancelled : "Completed" in value ? JobStatus.Completed : value;
}
function from_candid_PageSelection_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageSelection): PageSelection {
    return "All" in value ? PageSelection.All : "Custom" in value ? PageSelection.Custom : value;
}
function from_candid_PaperSize_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaperSize): PaperSize {
    return "A3" in value ? PaperSize.A3 : "A4" in value ? PaperSize.A4 : value;
}
function from_candid_PrintJobView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintJobView): PrintJobView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PrintOptions_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintOptions): PrintOptions {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PrintProgress_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintProgress): PrintProgress {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PrinterStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrinterStatus): PrinterStatus {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PrinterView_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrinterView): PrinterView {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UploadValidation_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadValidation): UploadValidation {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnalysisResultView]): AnalysisResultView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UploadedFileView]): UploadedFileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrintJobView]): PrintJobView | null {
    return value.length === 0 ? null : from_candid_PrintJobView_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrintProgress]): PrintProgress | null {
    return value.length === 0 ? null : from_candid_PrintProgress_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrinterView]): PrinterView | null {
    return value.length === 0 ? null : from_candid_PrinterView_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrinterStatus]): PrinterStatus | null {
    return value.length === 0 ? null : from_candid_PrinterStatus_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobId]): JobId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorMode: _ColorMode;
    excludedBlankPages: Array<bigint>;
    pageSelection: _PageSelection;
    paperSize: _PaperSize;
    customRange: [] | [string];
    copies: bigint;
}): {
    colorMode: ColorMode;
    excludedBlankPages: Array<bigint>;
    pageSelection: PageSelection;
    paperSize: PaperSize;
    customRange?: string;
    copies: bigint;
} {
    return {
        colorMode: from_candid_ColorMode_n11(_uploadFile, _downloadFile, value.colorMode),
        excludedBlankPages: value.excludedBlankPages,
        pageSelection: from_candid_PageSelection_n12(_uploadFile, _downloadFile, value.pageSelection),
        paperSize: from_candid_PaperSize_n13(_uploadFile, _downloadFile, value.paperSize),
        customRange: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.customRange)),
        copies: value.copies
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n22(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n26(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JobStatus;
    printedPages: bigint;
    jobId: _JobId;
    updatedAt: _Timestamp;
    totalPages: bigint;
}): {
    status: JobStatus;
    printedPages: bigint;
    jobId: JobId;
    updatedAt: Timestamp;
    totalPages: bigint;
} {
    return {
        status: from_candid_JobStatus_n8(_uploadFile, _downloadFile, value.status),
        printedPages: value.printedPages,
        jobId: value.jobId,
        updatedAt: value.updatedAt,
        totalPages: value.totalPages
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PrinterId;
    paperSizes: Array<_PaperSize>;
    colorModes: Array<_ColorMode>;
    speedPagesPerMinute: bigint;
    name: string;
    isOnline: boolean;
    description: string;
    openingHours: string;
    rating: bigint;
    location: string;
}): {
    id: PrinterId;
    paperSizes: Array<PaperSize>;
    colorModes: Array<ColorMode>;
    speedPagesPerMinute: bigint;
    name: string;
    isOnline: boolean;
    description: string;
    openingHours: string;
    rating: bigint;
    location: string;
} {
    return {
        id: value.id,
        paperSizes: from_candid_vec_n38(_uploadFile, _downloadFile, value.paperSizes),
        colorModes: from_candid_vec_n39(_uploadFile, _downloadFile, value.colorModes),
        speedPagesPerMinute: value.speedPagesPerMinute,
        name: value.name,
        isOnline: value.isOnline,
        description: value.description,
        openingHours: value.openingHours,
        rating: value.rating,
        location: value.location
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isOnline: boolean;
    updatedAt: _Timestamp;
    state: string;
    activeJobId: [] | [_JobId];
    printerId: _PrinterId;
}): {
    isOnline: boolean;
    updatedAt: Timestamp;
    state: string;
    activeJobId?: JobId;
    printerId: PrinterId;
} {
    return {
        isOnline: value.isOnline,
        updatedAt: value.updatedAt,
        state: value.state,
        activeJobId: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.activeJobId)),
        printerId: value.printerId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    estimatedPrice: bigint;
    printedPages: bigint;
    createdAt: _Timestamp;
    fileName: string;
    updatedAt: _Timestamp;
    fileId: _FileId;
    jobRef: _JobRef;
    sizeBytes: bigint;
    printerId: _PrinterId;
    options: _PrintOptions;
    pageCount: bigint;
}): {
    id: JobId;
    status: JobStatus;
    estimatedPrice: bigint;
    printedPages: bigint;
    createdAt: Timestamp;
    fileName: string;
    updatedAt: Timestamp;
    fileId: FileId;
    jobRef: JobRef;
    sizeBytes: bigint;
    printerId: PrinterId;
    options: PrintOptions;
    pageCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n8(_uploadFile, _downloadFile, value.status),
        estimatedPrice: value.estimatedPrice,
        printedPages: value.printedPages,
        createdAt: value.createdAt,
        fileName: value.fileName,
        updatedAt: value.updatedAt,
        fileId: value.fileId,
        jobRef: value.jobRef,
        sizeBytes: value.sizeBytes,
        printerId: value.printerId,
        options: from_candid_PrintOptions_n9(_uploadFile, _downloadFile, value.options),
        pageCount: value.pageCount
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AllowedExtension;
} | {
    unsupportedExtension: string;
} | {
    tooLarge: {
        actualBytes: bigint;
        limitBytes: bigint;
    };
} | {
    empty: null;
}): {
    __kind__: "ok";
    ok: AllowedExtension;
} | {
    __kind__: "unsupportedExtension";
    unsupportedExtension: string;
} | {
    __kind__: "tooLarge";
    tooLarge: {
        actualBytes: bigint;
        limitBytes: bigint;
    };
} | {
    __kind__: "empty";
    empty: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AllowedExtension_n48(_uploadFile, _downloadFile, value.ok)
    } : "unsupportedExtension" in value ? {
        __kind__: "unsupportedExtension",
        unsupportedExtension: value.unsupportedExtension
    } : "tooLarge" in value ? {
        __kind__: "tooLarge",
        tooLarge: value.tooLarge
    } : "empty" in value ? {
        __kind__: "empty",
        empty: value.empty
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaperSize>): Array<PaperSize> {
    return value.map((x)=>from_candid_PaperSize_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ColorMode>): Array<ColorMode> {
    return value.map((x)=>from_candid_ColorMode_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrintJobView>): Array<PrintJobView> {
    return value.map((x)=>from_candid_PrintJobView_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrinterView>): Array<PrinterView> {
    return value.map((x)=>from_candid_PrinterView_n36(_uploadFile, _downloadFile, x));
}
function to_candid_ColorMode_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorMode): _ColorMode {
    return value == ColorMode.BlackAndWhite ? {
        BlackAndWhite: null
    } : value == ColorMode.Color ? {
        Color: null
    } : value;
}
function to_candid_PageSelection_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageSelection): _PageSelection {
    return value == PageSelection.All ? {
        All: null
    } : value == PageSelection.Custom ? {
        Custom: null
    } : value;
}
function to_candid_PaperSize_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaperSize): _PaperSize {
    return value == PaperSize.A3 ? {
        A3: null
    } : value == PaperSize.A4 ? {
        A4: null
    } : value;
}
function to_candid_PrintOptions_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrintOptions): _PrintOptions {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorMode: ColorMode;
    excludedBlankPages: Array<bigint>;
    pageSelection: PageSelection;
    paperSize: PaperSize;
    customRange?: string;
    copies: bigint;
}): {
    colorMode: _ColorMode;
    excludedBlankPages: Array<bigint>;
    pageSelection: _PageSelection;
    paperSize: _PaperSize;
    customRange: [] | [string];
    copies: bigint;
} {
    return {
        colorMode: to_candid_ColorMode_n17(_uploadFile, _downloadFile, value.colorMode),
        excludedBlankPages: value.excludedBlankPages,
        pageSelection: to_candid_PageSelection_n18(_uploadFile, _downloadFile, value.pageSelection),
        paperSize: to_candid_PaperSize_n19(_uploadFile, _downloadFile, value.paperSize),
        customRange: value.customRange ? candid_some(value.customRange) : candid_none(),
        copies: value.copies
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
